# https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus.yml
---
global:
  # scrape_interval: 1m     # Default is 1m.
  # evaluation_interval: 1m # Default is 1m.
  # scrape_timeout: 10s     # Default is 10s.

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "loki"
    static_configs:
      - targets: [loki:3100]

  - job_name: "app"
    static_configs:
      - targets: [app:8080]
