# https://github.com/grafana/loki/blob/main/production/docker-compose.yaml
---
x-common-config: &common
  logging:
    driver: json-file
    options:
      tag: "{{.Name}}"
      max-size: "100m"
      max-file: "3"
  mem_limit: "512M"

services:
  app:
    <<: *common
    image: sh3b0/app_python:latest
    container_name: app
    ports:
      - "8080:8080"

  loki:
    <<: *common
    image: grafana/loki:latest
    container_name: loki
    # ports:
    #   - "3100:3100"
    volumes:
      - ./config:/mnt/config
    command: -config.file=/mnt/config/loki-config.yaml

  promtail:
    <<: *common
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers  # Needed for container logs
      - /var/log:/var/log
      - ./config:/mnt/config
    command: -config.file=/mnt/config/promtail-config.yaml

  grafana:
    <<: *common
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning

  prometheus:
    <<: *common
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config:/mnt/config
    command: --config.file=/mnt/config/prometheus-config.yaml
